# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest123():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test123(self):
    # Test name: test123
    # Step # | name | target | value
    # 1 | open | /datacrypto/ | 
    self.driver.get("https://192.168.106.113:3443/datacrypto/")
    # 2 | setWindowSize | 981x728 | 
    self.driver.set_window_size(981, 728)
    # 3 | click | id=loginId | 
    self.driver.find_element(By.ID, "loginId").click()
    # 4 | type | id=loginId | admin
    self.driver.find_element(By.ID, "loginId").send_keys("admin")
    # 5 | type | id=loginPassword | admin007
    self.driver.find_element(By.ID, "loginPassword").send_keys("admin007")
    # 6 | sendKeys | id=loginPassword | ${KEY_ENTER}
    self.driver.find_element(By.ID, "loginPassword").send_keys(Keys.ENTER)
    # 7 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 8 | click | css=.mainMenuElement:nth-child(1) > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".mainMenuElement:nth-child(1) > span").click()
    # 9 | click | css=.mainMenuElement:nth-child(1) .subMenuElement:nth-child(2) > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".mainMenuElement:nth-child(1) .subMenuElement:nth-child(2) > span").click()
    # 10 | mouseOver | css=.currentSubMenuElement > span | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".currentSubMenuElement > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 11 | click | css=.pnp-grid-new-icon-button:nth-child(3) | 
    self.driver.find_element(By.CSS_SELECTOR, ".pnp-grid-new-icon-button:nth-child(3)").click()
    # 12 | click | id=policyManageDialogName | 
    self.driver.find_element(By.ID, "policyManageDialogName").click()
    # 13 | type | id=policyManageDialogName | test01
    self.driver.find_element(By.ID, "policyManageDialogName").send_keys("test01")
    # 14 | click | css=.dialogElement:nth-child(6) .radioLabel:nth-child(2) > input | 
    self.driver.find_element(By.CSS_SELECTOR, ".dialogElement:nth-child(6) .radioLabel:nth-child(2) > input").click()
    # 15 | click | id=readUse | 
    self.driver.find_element(By.ID, "readUse").click()
    # 16 | click | id=accountButton | 
    self.driver.find_element(By.ID, "accountButton").click()
    # 17 | mouseOver | id=accountButton | 
    element = self.driver.find_element(By.ID, "accountButton")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 18 | mouseOut | id=accountButton | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 19 | click | id=objectGrid_resize_account | 
    self.driver.find_element(By.ID, "objectGrid_resize_account").click()
    # 20 | click | css=.ui-dialog:nth-child(10) .ui-button:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(10) .ui-button:nth-child(1)").click()
    # 21 | click | id=ipButton | 
    self.driver.find_element(By.ID, "ipButton").click()
    # 22 | mouseOver | id=ipButton | 
    element = self.driver.find_element(By.ID, "ipButton")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 23 | mouseOut | id=ipButton | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 24 | click | css=#objectGrid-row-3 input | 
    self.driver.find_element(By.CSS_SELECTOR, "#objectGrid-row-3 input").click()
    # 25 | click | css=.ui-dialog:nth-child(10) .ui-button:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(10) .ui-button:nth-child(1)").click()
    # 26 | click | id=processButton | 
    self.driver.find_element(By.ID, "processButton").click()
    # 27 | mouseOver | id=processButton | 
    element = self.driver.find_element(By.ID, "processButton")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 28 | mouseOut | id=processButton | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 29 | click | css=#objectGrid-row-1 > .td-selectable | 
    self.driver.find_element(By.CSS_SELECTOR, "#objectGrid-row-1 > .td-selectable").click()
    # 30 | click | css=.ui-dialog:nth-child(10) .ui-button:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(10) .ui-button:nth-child(1)").click()
    # 31 | click | css=.ui-dialog:nth-child(7) .ui-button:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(7) .ui-button:nth-child(1)").click()
    # 32 | mouseOver | css=.ui-dialog:nth-child(7) .ui-button:nth-child(1) | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog:nth-child(7) .ui-button:nth-child(1)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 33 | mouseOut | css=.ui-dialog:nth-child(7) .ui-button:nth-child(1) | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 34 | click | id=confirmMessageOk | 
    self.driver.find_element(By.ID, "confirmMessageOk").click()
    # 35 | mouseOver | id=confirmMessageOk | 
    element = self.driver.find_element(By.ID, "confirmMessageOk")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 36 | mouseOver | id=alertMessageOk | 
    element = self.driver.find_element(By.ID, "alertMessageOk")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 37 | mouseOut | id=alertMessageOk | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 38 | click | id=alertMessageOk | 
    self.driver.find_element(By.ID, "alertMessageOk").click()
    # 39 | click | css=.pnp-grid-head-wrap tr | 
    self.driver.find_element(By.CSS_SELECTOR, ".pnp-grid-head-wrap tr").click()
    # 40 | click | css=.mainMenuElement:nth-child(1) .subMenuElement:nth-child(1) > span | 
    self.driver.find_element(By.CSS_SELECTOR, ".mainMenuElement:nth-child(1) .subMenuElement:nth-child(1) > span").click()
    # 41 | click | css=.fa-plus | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa-plus").click()
    # 42 | mouseDownAt | id=ui-id-8 | 436.609375,2.421875
    element = self.driver.find_element(By.ID, "ui-id-8")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 43 | mouseMoveAt | id=ui-id-8 | 436.609375,2.421875
    element = self.driver.find_element(By.ID, "ui-id-8")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 44 | mouseUpAt | id=ui-id-8 | 436.609375,2.421875
    element = self.driver.find_element(By.ID, "ui-id-8")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 45 | click | id=ui-id-8 | 
    self.driver.find_element(By.ID, "ui-id-8").click()
    # 46 | click | name=unapplyDecryptGrid-checkbox | 
    self.driver.find_element(By.NAME, "unapplyDecryptGrid-checkbox").click()
    # 47 | mouseDownAt | id=ui-id-8 | 450.40625,94.421875
    element = self.driver.find_element(By.ID, "ui-id-8")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 48 | mouseMoveAt | css=.ui-dialog | 187,24.5
    element = self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 49 | mouseUpAt | css=.ui-dialog | 187,24.5
    element = self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 50 | click | id=ui-id-8 | 
    self.driver.find_element(By.ID, "ui-id-8").click()
    # 51 | click | css=.ui-dialog-buttonset > .ui-button:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".ui-dialog-buttonset > .ui-button:nth-child(1)").click()
    # 52 | click | css=.fa-floppy-o | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa-floppy-o").click()
    # 53 | click | id=confirmMessageOk | 
    self.driver.find_element(By.ID, "confirmMessageOk").click()
    # 54 | mouseOver | id=confirmMessageOk | 
    element = self.driver.find_element(By.ID, "confirmMessageOk")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 55 | click | id=alertMessageOk | 
    self.driver.find_element(By.ID, "alertMessageOk").click()
  
